### ISSUE TITLE
${DATETIME} causes autobuilder meltdown

### ISSUE THREAD

**Issue by koenkooi** [ndechesne/meta-qcom#10]
do_deploy and friends will be re-executed every build, leading to a lot of clutter (e.g. http://dominion.thruhere.net/angstrom/nightlies/v2015.12/dragonboard-410c/ ).

PRSERV should be used to get monotonically increasing versioning, not ${DATETIME}

**Comment by koenkooi** [comment]
This bug makes dependency testing (for recipes in recipes ; do bitbake recipe ; rm TMPDIR; done) take ages for qcom machines as well.

**Comment by ndechesne** [comment]
i agree.. i will fix that. this is valid for the boot image, and also the rootfs images..

**Comment by ndechesne** [comment]
I believe this is now fixed by commit b6d82b37dd4330d79450f0ae2936a0eb1dac34c4
