### ISSUE TITLE
Can I enable CSI/camera for 845c board?

### ISSUE THREAD

**Issue by sprhawk** [ndechesne/meta-qcom#119]
I am building yocto for Qualcomm RB3 ( Dragonboard 845c ).
But its camera cannot work under this version. 

I have seen [410c can enable it](https://www.96boards.org/documentation/consumer/dragonboard/dragonboard410c/guides/camera-module.md.html).

I wonder whether I can do similar for 845c?

I have enabled qcom-camss and ov8856 modules,  but I think what I am missing is correct DTS?

**Comment by ndechesne** [comment]
answered on 96boards forum.
