### ISSUE TITLE
Resize rootfs on first boot

### ISSUE THREAD

**Issue by koenkooi** [ndechesne/meta-qcom#3]
Out of the box there is very little space (~25MiB) available, we should try to resize the partition on first boot.

The following worked for me:

```
 opkg install e2fsprogs-resize2fs ; resize2fs  /dev/disk/by-partlabel/rootfs
```

My proposal is to have a recipe called something like 'resize-rootfs.bb' that RDEPENDS on e2fsprogs-resize2fs and does 'resize2fs  /dev/disk /by-partlabel/rootfs' as on-device postinst.

**Comment by ndechesne** [comment]
yes, i use resize2fs too. i wanted to find an elegant way to do that automatically.. so, we would add resize-rootfs in MACHINE_RRECOMMENDS? Did you make or are you planning to make the recipe?

**Comment by koenkooi** [comment]
I'm planning on making the recipe, I'm not sure where to put it though.

**Comment by ndechesne** [comment]
well, for now in recipes-bsp , in meta-qcom, it should be fine. it's not a generic recipe, since we are going to hardcode the name of the partition anyways.

**Comment by ndechesne** [comment]
this can be closed, the right tools are available in meta-96boards.
