### ISSUE TITLE
how to use aDSP of snapdragaon820

### ISSUE THREAD

**Issue by Madan1993** [ndechesne/meta-qcom#44]
i want play some mp3, mp4 etc file. i have alsa framework but it support only .raw, .wav file only. i am using yocto project . any framework or tool available ??

**Comment by ndechesne** [comment]
there is no support to do audio processing (codecs) on the aDSP at the moment. you will need to use software codecs (from Gstreamer, ffmpeg/libav, ... ) and then use the DSP for the RAW audio rendering.
